### ISSUE TITLE
Sobu thug guards detecting player weirdly

### ISSUE THREAD

**Issue by Tofu-Avenger** [scizz/darkfire#1]
I'm not sure if this is intentional, but there is a tile where if you walk behind the guard on it, they detect you and dont even turn around or move to you when speaking 

See a recording below
https://user-images.githubusercontent.com/109054466/178184264-0ae32850-d7f3-43f0-b27e-4dcd8291a777.mov

also this is minor and hard to see but as the screen fades to white, you can move for a couple frames.

**Comment by scizz** [comment]
Thank you for submitting, but this is a binary version issue. All binary development and support has been discontinued.

This repository aims to rebuild and further develop Darkfire using pret's pokeemerald decompilation project.
